version: '3'

services:
  db:
    image: mysql:8.0.33
    container_name: mysql_host
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: test
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    volumes:
    - ./docker/db/data:/var/lib/mysql
    - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
    - 3306:3306